# curl -d '{"title":"Black Panther","year":2018,"runtime":"134 mins","genres":["action","adventure"]}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title":"Black Panther","year":2018,"runtime":"134 mins","genres":["action","adventure"]}

###

# curl -d '{"title":"Deadpool","year":2016, "runtime":"108 mins","genres":["action","comedy"]}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title":"Deadpool","year":2016, "runtime":"108 mins","genres":["action","comedy"]}

###

# curl -d '{"title":"The Breakfast Club","year":1986, "runtime":"96 mins","genres":["drama"]}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title":"The Breakfast Club","year":1986, "runtime":"96 mins","genres":["drama"]}

###

# curl -i -d '{"title":"Moana","year":2016,"runtime":"107 mins","genres":["animation","adventure"]}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title":"Moana","year":2016,"runtime":"107 mins","genres":["animation","adventure"]}

###

# curl -i -d '{"title":"","year":1000,"runtime":"-123 mins","genres":["sci-fi","sci-fi"]}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title":"","year":1000,"runtime":"-123 mins","genres":["sci-fi","sci-fi"]}

###

# curl -d '{"title": "Moana", "runtime": "107 mins"}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title": "Moana", "runtime": "107 mins"}

###

# curl -d '{"title": "Moana", "runtime": 107}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title": "Moana", "runtime": 107}

###

# curl -d '{"title": "Moana", "runtime": "107 minutes"}' localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

{"title": "Moana", "runtime": "107 minutes"}

###

# curl -d @/tmp/largefile.json localhost:4000/v1/movies
POST localhost:4000/v1/movies
Content-Type: application/x-www-form-urlencoded

< ../tmp/largefile.json

###

POST http://localhost:4000/v1/movies
Content-Type: application/json

{
  "title": "Moana",
  "rating": "PG"
}

###

POST http://localhost:4000/v1/movies

{
  "title": "Moana"
}
{
  "title": "Top Gun"
}

###

POST http://localhost:4000/v1/movies

{
  "title": "Moana"
}
:~()

###

POST http://localhost:4000/v1/movies
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?><note><to>Alex</to></note>

###

POST http://localhost:4000/v1/movies

{
  "title": "Moana",
}

###

POST http://localhost:4000/v1/movies
Content-Type: application/json

["foo", "bar"]

###

POST http://localhost:4000/v1/movies
Content-Type: application/json

{
  "title": 123
}

###

POST http://localhost:4000/v1/movies

###

POST http://localhost:4000/v1/movies
Content-Type: application/json

{
  "title": "Moana",
  "year": 2016,
  "runtime": 107,
  "genres": [
    "animation",
    "adventure"
  ]
}

###

GET http://localhost:4000/v1/movies/123

###

GET http://localhost:4000/v1/movies/abc

###
